env:
  browser: true
  es2017: true
  node: true
  commonjs: true
  jest: true

#extends: ['htmlacademy/es6', 'plugin:react/recommended']

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module

plugins:
  - react
rules: {}

settings:
  react:
    version: '17'
